//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.06 at 11:28:12 PM VLAT 
//


package ru.ptkom.provisor.models.alias_list2;

import ru.ptkom.provisor.models.Marshallable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="request">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="filters" type="{}filtersType"/>
 *                 &lt;/all>
 *                 &lt;attribute name="domain" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="limit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="address_range" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cursor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "in")
public class In extends Marshallable {

    @XmlElement(required = true)
    protected In.Request request;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link In.Request }
     *     
     */
    public In.Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link In.Request }
     *     
     */
    public void setRequest(In.Request value) {
        this.request = value;
    }


    public In(String domain, String addressRange, String limit){
        Request request = new Request(domain, addressRange, limit);
        this.request = request;
    }

    public In(){}


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="filters" type="{}filtersType"/>
     *       &lt;/all>
     *       &lt;attribute name="domain" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="limit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="address_range" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cursor" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Request {

        @XmlElement(required = true)
        protected FiltersType filters;
        @XmlAttribute(name = "domain", required = true)
        protected String domain;
        @XmlAttribute(name = "limit", required = true)
        protected String limit;
        @XmlAttribute(name = "address_range")
        protected String addressRange;
        @XmlAttribute(name = "cursor")
        protected String cursor;


        public Request(String domain, String addressRange, String limit) {
            this.domain = domain;
            this.addressRange = addressRange;
            this.limit = limit;
            this.filters = new FiltersType();
        }

        public Request() {

        }

        /**
         * Gets the value of the filters property.
         * 
         * @return
         *     possible object is
         *     {@link FiltersType }
         *     
         */
        public FiltersType getFilters() {
            return filters;
        }

        /**
         * Sets the value of the filters property.
         * 
         * @param value
         *     allowed object is
         *     {@link FiltersType }
         *     
         */
        public void setFilters(FiltersType value) {
            this.filters = value;
        }

        /**
         * Gets the value of the domain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDomain() {
            return domain;
        }

        /**
         * Sets the value of the domain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDomain(String value) {
            this.domain = value;
        }

        /**
         * Gets the value of the limit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLimit() {
            return limit;
        }

        /**
         * Sets the value of the limit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLimit(String value) {
            this.limit = value;
        }

        /**
         * Gets the value of the addressRange property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddressRange() {
            return addressRange;
        }

        /**
         * Sets the value of the addressRange property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddressRange(String value) {
            this.addressRange = value;
        }

        /**
         * Gets the value of the cursor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCursor() {
            return cursor;
        }

        /**
         * Sets the value of the cursor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCursor(String value) {
            this.cursor = value;
        }

    }

}
