//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.07 at 12:50:14 AM VLAT 
//


package ru.ptkom.provisor.models.sip_user_show;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for displayEncodingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="displayEncodingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="default"/>
 *     &lt;enumeration value="win1251"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "displayEncodingType")
@XmlEnum
public enum DisplayEncodingType {

    @XmlEnumValue("default")
    DEFAULT("default"),
    @XmlEnumValue("win1251")
    WIN_1251("win1251");
    private final String value;

    DisplayEncodingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DisplayEncodingType fromValue(String v) {
        for (DisplayEncodingType c: DisplayEncodingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
