//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.07 at 12:50:14 AM VLAT 
//


package ru.ptkom.provisor.models.sip_user_show;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="active" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="alarm_enable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="aliases_list" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="auth" type="{}authTypeType" />
 *       &lt;attribute name="auth_qop" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="digest" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="contact" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="domain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fork_mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fixed_contact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iface" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="login" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="last_via" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nat_traversal" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="referred_by_as_cgpn" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="reg_expire_min" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="reg_expire_max" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="rfc4028_control" type="{}rfc4028ControlType" />
 *       &lt;attribute name="routing_context" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modificator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="symbol_hash_as_is" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="tel_uri_in_diversion" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="tel_uri_using" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="sip_domain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sip_modifications" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="req100rel" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="dtmf_relay" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="original_cdpn_to" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="my_from" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="auto_answer_version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="display_encoding" type="{}displayEncodingType" />
 *       &lt;attribute name="remote_ctr_indication" type="{}remoteCtrIndicationType" />
 *       &lt;attribute name="category_to_sip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="registered_domain_to_invite" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="trusted_ip" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="user_agent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userType")
public class UserType {

    @XmlAttribute(name = "active", required = true)
    protected boolean active;
    @XmlAttribute(name = "alarm_enable")
    protected Boolean alarmEnable;
    @XmlAttribute(name = "aliases_list")
    protected String aliasesList;
    @XmlAttribute(name = "auth")
    protected AuthTypeType auth;
    @XmlAttribute(name = "auth_qop")
    protected String authQop;
    @XmlAttribute(name = "digest")
    protected Boolean digest;
    @XmlAttribute(name = "contact", required = true)
    protected String contact;
    @XmlAttribute(name = "domain")
    protected String domain;
    @XmlAttribute(name = "fork_mode")
    protected String forkMode;
    @XmlAttribute(name = "fixed_contact")
    protected String fixedContact;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "group", required = true)
    protected String group;
    @XmlAttribute(name = "iface", required = true)
    protected String iface;
    @XmlAttribute(name = "login")
    protected String login;
    @XmlAttribute(name = "last_via")
    protected String lastVia;
    @XmlAttribute(name = "nat_traversal")
    protected Boolean natTraversal;
    @XmlAttribute(name = "owner")
    protected String owner;
    @XmlAttribute(name = "password")
    protected String password;
    @XmlAttribute(name = "referred_by_as_cgpn")
    protected Boolean referredByAsCgpn;
    @XmlAttribute(name = "reg_expire_min")
    protected BigInteger regExpireMin;
    @XmlAttribute(name = "reg_expire_max")
    protected BigInteger regExpireMax;
    @XmlAttribute(name = "rfc4028_control")
    protected Rfc4028ControlType rfc4028Control;
    @XmlAttribute(name = "routing_context")
    protected String routingContext;
    @XmlAttribute(name = "modificator")
    protected String modificator;
    @XmlAttribute(name = "symbol_hash_as_is")
    protected Boolean symbolHashAsIs;
    @XmlAttribute(name = "tel_uri_in_diversion")
    protected Boolean telUriInDiversion;
    @XmlAttribute(name = "tel_uri_using")
    protected Boolean telUriUsing;
    @XmlAttribute(name = "sip_domain")
    protected String sipDomain;
    @XmlAttribute(name = "sip_modifications")
    protected String sipModifications;
    @XmlAttribute(name = "req100rel")
    protected Boolean req100Rel;
    @XmlAttribute(name = "dtmf_relay")
    protected Boolean dtmfRelay;
    @XmlAttribute(name = "original_cdpn_to")
    protected Boolean originalCdpnTo;
    @XmlAttribute(name = "my_from")
    protected String myFrom;
    @XmlAttribute(name = "transit")
    protected String transit;
    @XmlAttribute(name = "auto_answer_version")
    protected String autoAnswerVersion;
    @XmlAttribute(name = "display_encoding")
    protected DisplayEncodingType displayEncoding;
    @XmlAttribute(name = "remote_ctr_indication")
    protected RemoteCtrIndicationType remoteCtrIndication;
    @XmlAttribute(name = "category_to_sip")
    protected String categoryToSip;
    @XmlAttribute(name = "registered_domain_to_invite")
    protected Boolean registeredDomainToInvite;
    @XmlAttribute(name = "trusted_ip")
    protected String trustedIp;
    @XmlAttribute(name = "user_agent")
    protected String userAgent;

    /**
     * Gets the value of the active property.
     * 
     */
    public boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     */
    public void setActive(boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the alarmEnable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAlarmEnable() {
        return alarmEnable;
    }

    /**
     * Sets the value of the alarmEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAlarmEnable(Boolean value) {
        this.alarmEnable = value;
    }

    /**
     * Gets the value of the aliasesList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasesList() {
        return aliasesList;
    }

    /**
     * Sets the value of the aliasesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasesList(String value) {
        this.aliasesList = value;
    }

    /**
     * Gets the value of the auth property.
     * 
     * @return
     *     possible object is
     *     {@link AuthTypeType }
     *     
     */
    public AuthTypeType getAuth() {
        return auth;
    }

    /**
     * Sets the value of the auth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthTypeType }
     *     
     */
    public void setAuth(AuthTypeType value) {
        this.auth = value;
    }

    /**
     * Gets the value of the authQop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthQop() {
        return authQop;
    }

    /**
     * Sets the value of the authQop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthQop(String value) {
        this.authQop = value;
    }

    /**
     * Gets the value of the digest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDigest() {
        return digest;
    }

    /**
     * Sets the value of the digest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDigest(Boolean value) {
        this.digest = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the forkMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForkMode() {
        return forkMode;
    }

    /**
     * Sets the value of the forkMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForkMode(String value) {
        this.forkMode = value;
    }

    /**
     * Gets the value of the fixedContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedContact() {
        return fixedContact;
    }

    /**
     * Sets the value of the fixedContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedContact(String value) {
        this.fixedContact = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the iface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIface() {
        return iface;
    }

    /**
     * Sets the value of the iface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIface(String value) {
        this.iface = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the lastVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastVia() {
        return lastVia;
    }

    /**
     * Sets the value of the lastVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastVia(String value) {
        this.lastVia = value;
    }

    /**
     * Gets the value of the natTraversal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNatTraversal() {
        return natTraversal;
    }

    /**
     * Sets the value of the natTraversal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNatTraversal(Boolean value) {
        this.natTraversal = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the referredByAsCgpn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReferredByAsCgpn() {
        return referredByAsCgpn;
    }

    /**
     * Sets the value of the referredByAsCgpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferredByAsCgpn(Boolean value) {
        this.referredByAsCgpn = value;
    }

    /**
     * Gets the value of the regExpireMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRegExpireMin() {
        return regExpireMin;
    }

    /**
     * Sets the value of the regExpireMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRegExpireMin(BigInteger value) {
        this.regExpireMin = value;
    }

    /**
     * Gets the value of the regExpireMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRegExpireMax() {
        return regExpireMax;
    }

    /**
     * Sets the value of the regExpireMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRegExpireMax(BigInteger value) {
        this.regExpireMax = value;
    }

    /**
     * Gets the value of the rfc4028Control property.
     * 
     * @return
     *     possible object is
     *     {@link Rfc4028ControlType }
     *     
     */
    public Rfc4028ControlType getRfc4028Control() {
        return rfc4028Control;
    }

    /**
     * Sets the value of the rfc4028Control property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rfc4028ControlType }
     *     
     */
    public void setRfc4028Control(Rfc4028ControlType value) {
        this.rfc4028Control = value;
    }

    /**
     * Gets the value of the routingContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutingContext() {
        return routingContext;
    }

    /**
     * Sets the value of the routingContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutingContext(String value) {
        this.routingContext = value;
    }

    /**
     * Gets the value of the modificator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificator() {
        return modificator;
    }

    /**
     * Sets the value of the modificator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificator(String value) {
        this.modificator = value;
    }

    /**
     * Gets the value of the symbolHashAsIs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSymbolHashAsIs() {
        return symbolHashAsIs;
    }

    /**
     * Sets the value of the symbolHashAsIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSymbolHashAsIs(Boolean value) {
        this.symbolHashAsIs = value;
    }

    /**
     * Gets the value of the telUriInDiversion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTelUriInDiversion() {
        return telUriInDiversion;
    }

    /**
     * Sets the value of the telUriInDiversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTelUriInDiversion(Boolean value) {
        this.telUriInDiversion = value;
    }

    /**
     * Gets the value of the telUriUsing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTelUriUsing() {
        return telUriUsing;
    }

    /**
     * Sets the value of the telUriUsing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTelUriUsing(Boolean value) {
        this.telUriUsing = value;
    }

    /**
     * Gets the value of the sipDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSipDomain() {
        return sipDomain;
    }

    /**
     * Sets the value of the sipDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSipDomain(String value) {
        this.sipDomain = value;
    }

    /**
     * Gets the value of the sipModifications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSipModifications() {
        return sipModifications;
    }

    /**
     * Sets the value of the sipModifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSipModifications(String value) {
        this.sipModifications = value;
    }

    /**
     * Gets the value of the req100Rel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReq100Rel() {
        return req100Rel;
    }

    /**
     * Sets the value of the req100Rel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReq100Rel(Boolean value) {
        this.req100Rel = value;
    }

    /**
     * Gets the value of the dtmfRelay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDtmfRelay() {
        return dtmfRelay;
    }

    /**
     * Sets the value of the dtmfRelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDtmfRelay(Boolean value) {
        this.dtmfRelay = value;
    }

    /**
     * Gets the value of the originalCdpnTo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOriginalCdpnTo() {
        return originalCdpnTo;
    }

    /**
     * Sets the value of the originalCdpnTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOriginalCdpnTo(Boolean value) {
        this.originalCdpnTo = value;
    }

    /**
     * Gets the value of the myFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMyFrom() {
        return myFrom;
    }

    /**
     * Sets the value of the myFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMyFrom(String value) {
        this.myFrom = value;
    }

    /**
     * Gets the value of the transit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransit() {
        return transit;
    }

    /**
     * Sets the value of the transit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransit(String value) {
        this.transit = value;
    }

    /**
     * Gets the value of the autoAnswerVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAnswerVersion() {
        return autoAnswerVersion;
    }

    /**
     * Sets the value of the autoAnswerVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAnswerVersion(String value) {
        this.autoAnswerVersion = value;
    }

    /**
     * Gets the value of the displayEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayEncodingType }
     *     
     */
    public DisplayEncodingType getDisplayEncoding() {
        return displayEncoding;
    }

    /**
     * Sets the value of the displayEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayEncodingType }
     *     
     */
    public void setDisplayEncoding(DisplayEncodingType value) {
        this.displayEncoding = value;
    }

    /**
     * Gets the value of the remoteCtrIndication property.
     * 
     * @return
     *     possible object is
     *     {@link RemoteCtrIndicationType }
     *     
     */
    public RemoteCtrIndicationType getRemoteCtrIndication() {
        return remoteCtrIndication;
    }

    /**
     * Sets the value of the remoteCtrIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoteCtrIndicationType }
     *     
     */
    public void setRemoteCtrIndication(RemoteCtrIndicationType value) {
        this.remoteCtrIndication = value;
    }

    /**
     * Gets the value of the categoryToSip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryToSip() {
        return categoryToSip;
    }

    /**
     * Sets the value of the categoryToSip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryToSip(String value) {
        this.categoryToSip = value;
    }

    /**
     * Gets the value of the registeredDomainToInvite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegisteredDomainToInvite() {
        return registeredDomainToInvite;
    }

    /**
     * Sets the value of the registeredDomainToInvite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegisteredDomainToInvite(Boolean value) {
        this.registeredDomainToInvite = value;
    }

    /**
     * Gets the value of the trustedIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrustedIp() {
        return trustedIp;
    }

    /**
     * Sets the value of the trustedIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrustedIp(String value) {
        this.trustedIp = value;
    }

    /**
     * Gets the value of the userAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }

}
